docs/AboutUs.md

Updated AboutUs.md

---

src/main/java/seedu/address/model/tag/Tag.java
src/test/java/guitests/FindCommandTest.java

Public String toString() {
return '[' + tagName + ']';
}		     
to
Public String toString() {
return ' ' + tagName + ' ';
}

TestCase-FindCmd + edit-Tag.toString()

---

src/main/java/seedu/address/commons/core/ComponentManager.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/CommandHistory.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/MarkCommand.java
src/main/java/seedu/address/logic/commands/UndoCommand.java
src/main/java/seedu/address/logic/parser/Parser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/TaskScheduler.java
src/main/java/seedu/address/model/Undo.java
src/main/java/seedu/address/model/task/Task.java
src/main/java/seedu/address/model/task/UniqueTaskList.java
src/test/java/guitests/UndoCommandTest.java

undo cmd for added, deleted, edited and marked tasks.

Add undo cmd

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/UndoCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/TaskScheduler.java
src/main/java/seedu/address/model/task/UniqueTaskList.java
src/test/java/guitests/UndoCommandTest.java

Fix Undo DeleteCommand Bug

---

src/main/java/seedu/address/ui/CommandBox.java
src/main/java/seedu/address/ui/UiPart.java

Reverts CS2103AUG2016-F09-C2/main#40

Revert "Up down arrow"

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/CommandHistory.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/RecurCommand.java
src/main/java/seedu/address/logic/commands/UndoCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/CommandParser.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/RecurCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/Undo.java
src/main/java/seedu/address/model/task/DeadlineTask.java
src/main/java/seedu/address/model/task/EventTask.java
src/main/java/seedu/address/model/task/FloatingTask.java
src/main/java/seedu/address/model/task/ReadOnlyTask.java
src/main/java/seedu/address/model/task/Task.java
src/main/java/seedu/address/model/task/TaskDateTime.java
src/test/java/guitests/UndoCommandTest.java
src/test/java/seedu/address/testutil/TestTask.java

Add recur command

---

docs/UserGuide.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/69)

Modified Userguide

---

src/main/java/seedu/taskscheduler/logic/commands/DeleteCommand.java
src/main/java/seedu/taskscheduler/model/task/UniqueTaskList.java
src/main/java/seedu/taskscheduler/ui/UiManager.java
src/test/java/guitests/AddCommandTest.java
src/test/java/guitests/FindCommandTest.java
src/test/java/guitests/RecurCommandTest.java
src/test/java/guitests/ReplaceCommandTest.java
src/test/java/guitests/guihandles/TaskListPanelHandle.java
src/test/java/seedu/taskscheduler/testutil/TypicalTestTasks.java
taskscheduler.xml
testtaskscheduler.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/80)

Add Date time sorted

---

collated/docs/A0138696L.md
docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/taskscheduler/ui/BrowserPanel.java
src/main/java/seedu/taskscheduler/ui/CommandBox.java
src/main/java/seedu/taskscheduler/ui/MainWindow.java
src/main/java/seedu/taskscheduler/ui/PriorityListPanel.java
src/main/java/seedu/taskscheduler/ui/UiManager.java
src/main/resources/view/MainWindow.fxml
src/main/resources/view/PriorityListPanel.fxml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/78)

Replace right panel

---

src/main/java/seedu/taskscheduler/MainApp.java
src/main/java/seedu/taskscheduler/storage/StorageManager.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/77)

Modify setpath

---

docs/AboutUs.md

Ready for merging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/81)

Updates aboutus.md

---

src/main/java/seedu/taskscheduler/logic/commands/UnmarkCommand.java
src/main/java/seedu/taskscheduler/logic/parser/UnmarkCommandParser.java
src/test/java/guitests/UnMarkCommandTest.java
src/test/java/guitests/UndoCommandTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/79)

added-UnmarkCommand

---

src/main/java/seedu/taskscheduler/logic/commands/CommandHistory.java
src/main/java/seedu/taskscheduler/logic/commands/SetpathCommand.java
src/main/java/seedu/taskscheduler/storage/StorageManager.java
src/test/java/guitests/SetPathCommandTest.java

Without test cases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/89)

Undo setpath 

---

src/main/java/seedu/taskscheduler/commons/events/ui/TaskPanelItemChangedEvent.java
src/main/java/seedu/taskscheduler/logic/Logic.java
src/main/java/seedu/taskscheduler/logic/LogicManager.java
src/main/java/seedu/taskscheduler/logic/commands/EditCommand.java
src/main/java/seedu/taskscheduler/model/Model.java
src/main/java/seedu/taskscheduler/model/ModelManager.java
src/main/java/seedu/taskscheduler/model/task/ReadOnlyTask.java
src/main/java/seedu/taskscheduler/model/task/Task.java
src/main/java/seedu/taskscheduler/model/task/TaskDateTime.java
src/main/java/seedu/taskscheduler/model/task/UniqueTaskList.java
src/main/java/seedu/taskscheduler/ui/MainWindow.java
src/main/java/seedu/taskscheduler/ui/PriorityListPanel.java
src/main/java/seedu/taskscheduler/ui/TaskListPanel.java
src/main/java/seedu/taskscheduler/ui/UiManager.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml
src/test/java/guitests/EditCommandTest.java
src/test/java/seedu/taskscheduler/testutil/TestTask.java

- Shows numbers of completed, pending and overdue tasks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/91)

Add MainWindow labels

---

docs/AboutUs.md
src/main/java/seedu/taskscheduler/commons/events/ui/CommandBoxTextChangeRequestEvent.java
src/main/java/seedu/taskscheduler/commons/util/TaskUtil.java
src/main/java/seedu/taskscheduler/logic/commands/CopyCommand.java
src/main/java/seedu/taskscheduler/logic/commands/SelectCommand.java
src/main/java/seedu/taskscheduler/ui/CommandBox.java
src/main/java/seedu/taskscheduler/ui/MainWindow.java
src/main/java/seedu/taskscheduler/ui/UiManager.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/92)

add select feature

---

collated/docs/A0138696L.md
collated/main/A0138696L.md
collated/main/A0140007B.md
collated/main/A0148145E.md
collated/test/A0138696L.md
collated/test/A0140007B.md
collated/test/A0148145E.md
collatew.bat
src/main/java/seedu/taskscheduler/model/TaskScheduler.java
src/main/java/seedu/taskscheduler/model/task/ReadOnlyTask.java
src/main/java/seedu/taskscheduler/ui/PriorityListPanel.java
src/test/java/guitests/AddCommandTest.java
src/test/java/guitests/DeleteCommandTest.java
src/test/java/guitests/EditCommandTest.java
src/test/java/guitests/FindCommandTest.java
src/test/java/guitests/RecurCommandTest.java
src/test/java/guitests/ReplaceCommandTest.java
src/test/java/guitests/UndoCommandTest.java
src/test/java/guitests/UnmarkCommandTest.java
src/test/java/guitests/UpDownButtonTest.java
src/test/java/seedu/taskscheduler/testutil/TestTask.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/95)

Fix prioritylist & testcase naming convention

---

src/main/java/seedu/taskscheduler/logic/commands/CommandHistory.java
src/main/java/seedu/taskscheduler/logic/parser/ReplaceCommandParser.java
src/main/java/seedu/taskscheduler/logic/parser/SetpathCommandParser.java
src/main/java/seedu/taskscheduler/logic/parser/UnmarkCommandParser.java
src/main/java/seedu/taskscheduler/model/Model.java
src/main/java/seedu/taskscheduler/model/TaskScheduler.java
src/main/java/seedu/taskscheduler/model/task/ReadOnlyTask.java
src/main/java/seedu/taskscheduler/model/task/UniqueTaskList.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/96)

Fix feed back

---

docs/DeveloperGuide.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/103)

update user story - find

---

docs/UserGuide.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/107)

Edit UserGuide

---

docs/UserGuide.md

Reverts CS2103AUG2016-F09-C2/main#107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/109)

Revert "Edit UserGuide"

---

docs/AboutUs.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/112)

Update AboutUs and fix link

---

README.md
collated/docs/A0138696L.md
collated/docs/A0140007B.md
collated/docs/A0148145E.md
collated/test/A0138696L.md
collated/test/A0148145E.md
docs/AboutUs.md
docs/UserGuide.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/116)

Reallign userguide ui quickguide

---

src/main/java/seedu/taskscheduler/logic/commands/SetpathCommand.java

Implemented delete previous file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/97)

modify-setpath

---

src/main/java/seedu/taskscheduler/MainApp.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/117)

Modified mainApp 

---

docs/UserGuide.md
src/main/java/seedu/taskscheduler/logic/commands/ExportCommand.java
src/main/java/seedu/taskscheduler/logic/commands/ImportCommand.java
src/main/java/seedu/taskscheduler/logic/commands/SetpathCommand.java

Please Check Thru.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/125)

Amended to path docs and prompt messages

---

collated/main/A0138696L.md
src/main/java/seedu/taskscheduler/logic/commands/UnmarkCommand.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cs2103aug2016-f09-c2/main/129)

Modify-Unmarkcmd coding standard

---

src/main/java/seedu/taskscheduler/model/task/Name.java
src/main/java/seedu/taskscheduler/model/task/ReadOnlyTask.java
src/main/java/seedu/taskscheduler/model/task/TaskDateTime.java
src/main/java/seedu/taskscheduler/model/task/UniqueTaskList.java

Order floating task alphabetically #149
